new ArticleCodeConfigData(0, 0, 0, "FACT_UNKNOWN", ),
new ArticleCodeConfigData(1, 1, 0, "FACT_CONTRACT_TERM", ),
new ArticleCodeConfigData(2, 2, 1, "FACT_CONTRACT_TIMESHEET", 1, 8),
new ArticleCodeConfigData(3, 3, 1, "FACT_CONTRACT_WORKING", 2, 9),
new ArticleCodeConfigData(5, 5, 1, "FACT_CONTRACT_ATTEND_ITEM", 2),
new ArticleCodeConfigData(4, 4, 1, "FACT_CONTRACT_ABSENCE", 2, 10),
new ArticleCodeConfigData(6, 6, 1, "FACT_POSITION_TERM", 1),
new ArticleCodeConfigData(7, 7, 2, "FACT_POSITION_SCHEDULE", 6),
new ArticleCodeConfigData(8, 8, 2, "FACT_POSITION_TIMESHEET", 7),
new ArticleCodeConfigData(9, 9, 2, "FACT_POSITION_WORKING", 8),
new ArticleCodeConfigData(10, 10, 2, "FACT_POSITION_ABSENCE", 8, 5),

new ArticleRoleConfigData(0, "ARTICLE_UNKNOWN"),
new ArticleRoleConfigData(1, "ARTICLE_CONTRACT_TERM"),
new ArticleRoleConfigData(6, "ARTICLE_POSITION_TERM"),
new ArticleRoleConfigData(7, "ARTICLE_POSITION_SCHEDULE"),
new ArticleRoleConfigData(8, "ARTICLE_POSITION_TIMESHEET"),
new ArticleRoleConfigData(9, "ARTICLE_POSITION_WORKING"),
new ArticleRoleConfigData(10, "ARTICLE_POSITION_ABSENCE"),
new ArticleRoleConfigData(2, "ARTICLE_CONTRACT_TIMESHEET"),
new ArticleRoleConfigData(3, "ARTICLE_CONTRACT_WORKING"),
new ArticleRoleConfigData(4, "ARTICLE_CONTRACT_ABSENCE"),
new ArticleRoleConfigData(5, "ARTICLE_CONTRACT_ATTEND_ITEM"),
