using System;

namespace ElementsLib.Module.Codes
{
    using EnumCode = UInt16;
    public enum ArticleRoleCz : EnumCode
    {
        METHOD_UNKNOWN = 0,
        METHOD_CONTRACT_TERM,
        METHOD_POSITION_TERM,
        METHOD_POSITION_SCHEDULE,
        METHOD_POSITION_TIMESHEET,
        METHOD_POSITION_WORKING,
        METHOD_POSITION_ABSENCE,
        METHOD_CONTRACT_TIMESHEET,
        METHOD_CONTRACT_WORKING,
        METHOD_CONTRACT_ABSENCE,
        //METHOD_POSITION_MONTHLY_AMOUNT,
        //METHOD_TAX_DECLARATION,
        //METHOD_INS_HEALTH_DECLARATION,
        //METHOD_INS_SOCIAL_DECLARATION,
        //METHOD_TAX_INCOMES_GENERAL,
        //METHOD_TAX_INCOMES_ADVANCE,
        //METHOD_TAX_INCOMES_WITHHOLD,
        //METHOD_INS_INCOMES_HEALTH,
        //METHOD_INS_INCOMES_SOCIAL,
        //METHOD_TAX_ADVANCE_BASE,
        //METHOD_TAX_ADVANCE_HEALTH,
        //METHOD_TAX_ADVANCE_SOCIAL,
        //METHOD_TAX_ADVANCE_PART,
        //METHOD_TAX_SOLIDARY_BASE,
        //METHOD_TAX_ADVANCE,
        //METHOD_TAX_SOLIDARY,
        //METHOD_TAX_ADVANCE_FINAL,
        //METHOD_TAX_WITHHOLD_BASE,
        //METHOD_TAX_WITHHOLD_HEALTH,
        //METHOD_TAX_WITHHOLD_SOCIAL,
        //METHOD_TAX_WITHHOLD_PART,
        //METHOD_TAX_WITHHOLD_FINAL,
        //METHOD_TAX_CLAIM_PAYER,
        //METHOD_TAX_CLAIM_DISABILITY,
        //METHOD_TAX_CLAIM_STUDYING,
        //METHOD_TAX_CLAIM_CHILD,
        //METHOD_TAX_RELIEF_PAYER,
        //METHOD_TAX_RELIEF_CHILD,
        //METHOD_TAX_BONUS_CHILD,
        //METHOD_INS_HEALTH_BASE,
        //METHOD_INS_HEALTH_FINAL,
        //METHOD_INS_SOCIAL_BASE,
        //METHOD_INS_SOCIAL_FINAL,
        //METHOD_INCOME_GROSS,
        //METHOD_INCOME_NETTO
    }
    public static class ArticleCzRoleExtensions
    {
        public static string GetSymbol(this ArticleRoleCz article)
        {
            return article.ToString();
        }
    }
}
