using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ElementsLib
{
    public enum ArticleCode : UInt16
    {
        ARTICLE_UNKNOWN = 0,
        ARTICLE_CONTRACT_TERM,
        ARTICLE_POSITION_TERM,
        ARTICLE_POSITION_SCHEDULE,
        ARTICLE_POSITION_TIMESHEET,
        ARTICLE_POSITION_WORKING,
        ARTICLE_POSITION_ABSENCE,
        ARTICLE_CONTRACT_TIMESHEET,
        ARTICLE_CONTRACT_WORKING,
        ARTICLE_CONTRACT_ABSENCE,
        //ARTICLE_POSITION_MONTHLY_AMOUNT,
        //ARTICLE_TAX_DECLARATION,
        //ARTICLE_INS_HEALTH_DECLARATION,
        //ARTICLE_INS_SOCIAL_DECLARATION,
        //ARTICLE_TAX_INCOMES_GENERAL,
        //ARTICLE_TAX_INCOMES_ADVANCE,
        //ARTICLE_TAX_INCOMES_WITHHOLD,
        //ARTICLE_INS_INCOMES_HEALTH,
        //ARTICLE_INS_INCOMES_SOCIAL,
        //ARTICLE_TAX_ADVANCE_BASE,
        //ARTICLE_TAX_ADVANCE_HEALTH,
        //ARTICLE_TAX_ADVANCE_SOCIAL,
        //ARTICLE_TAX_ADVANCE_PART,
        //ARTICLE_TAX_SOLIDARY_BASE,
        //ARTICLE_TAX_ADVANCE,
        //ARTICLE_TAX_SOLIDARY,
        //ARTICLE_TAX_ADVANCE_FINAL,
        //ARTICLE_TAX_WITHHOLD_BASE,
        //ARTICLE_TAX_WITHHOLD_HEALTH,
        //ARTICLE_TAX_WITHHOLD_SOCIAL,
        //ARTICLE_TAX_WITHHOLD_PART,
        //ARTICLE_TAX_WITHHOLD_FINAL,
        //ARTICLE_TAX_CLAIM_PAYER,
        //ARTICLE_TAX_CLAIM_DISABILITY,
        //ARTICLE_TAX_CLAIM_STUDYING,
        //ARTICLE_TAX_CLAIM_CHILD,
        //ARTICLE_TAX_RELIEF_PAYER,
        //ARTICLE_TAX_RELIEF_CHILD,
        //ARTICLE_TAX_BONUS_CHILD,
        //ARTICLE_INS_HEALTH_BASE,
        //ARTICLE_INS_HEALTH_FINAL,
        //ARTICLE_INS_SOCIAL_BASE,
        //ARTICLE_INS_SOCIAL_FINAL,
        //ARTICLE_INCOME_GROSS,
        //ARTICLE_INCOME_NETTO
    }
    public static class ArticleCodeExtensions
    {
        public static string GetSymbol(this ArticleCode article)
        {
            return article.ToString();
        }
    }
}
